# Generated by Django 2.2.28 on 2023-08-16 15:22

import colorfield.fields
from django.db import migrations, models
import recipes.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Тег с таким названием уже существует.'}, max_length=200, unique=True, verbose_name='Название Тега')),
                ('color', colorfield.fields.ColorField(blank=True, default='#ffd057', error_messages={'unique': 'Такой цвет уже существует.'}, image_field=None, max_length=7, null=True, samples=None, unique=True, validators=[recipes.validate.validate_color], verbose_name='Цвет в HeX')),
                ('slug', models.CharField(error_messages={'unique': 'Такой Slug уже существует.'}, max_length=200, unique=True, validators=[recipes.validate.validate_slug], verbose_name='Уникальный Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
