# Generated by Django 2.2.28 on 2023-08-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230824_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingсart',
            options={'default_related_name': 'shopping_list', 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
